### ISSUE TITLE
[BUG] Auction

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#92] opened 2020-02-11 23:17 UTC
**Describe the bug**
I can't place bid in the auction (with Tronlink)

**To Reproduce**
1. Go to 'auction'
2. Select amount
3. Click on 'Bid and burn'
4. See error: I cant confirm the transaction

With a bid less than 0,1 games show me error ( i cant place bid less than 0,1)
if i try to place bid 0,1 or more it doesn't work

**Source**
 - Device: [ PC]
 - OS: [ windows 10]
 - Browser [chromei]
 - Browser Version [last]
 - Platform Version [0.2.0]

**Comment by digforit** [comment] 2020-02-14 11:42
duplicate of #71

**Comment by digforit** [comment] 2020-02-14 11:43
Duplicate of #71

**Closed as completed** 2020-02-14 11:43 UTC
Labels: bug
