### ISSUE TITLE
[FEATURE] Area tools on a random point

### ISSUE THREAD

**Issue by JackYnTheBox** [digforit/platform#62] opened 2020-01-25 01:30 UTC
**Is your feature request related to a problem? Please describe.**
When I use the tools on the whole 10x10 map as meteor shower or lightning, I have to press on an undestroyed tile and not on a random point on the 10x10 map

**Describe the solution you'd like**
I would prefer not to have to press on a complete tile but on a random point on the map to active this type of tools

**Comment by digforit** [comment] 2020-01-25 19:27
Duplicate of #54

**Closed as completed by digforit** 2020-01-25 19:27 UTC
Labels: feature, duplicate
